### ISSUE TITLE
no example folder for postgres

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-postgres#1]
Hello, 
contrary to your other beautiful images, you didn't include docker-compose samples here in postrgres. 
Left on purpose for the excercise of the user?

**Comment by tiredofit** [comment]
Thanks for the compliment - Let me add some shortly and add a new branch for 12.

**Comment by tiredofit** [comment]
See this for example: https://github.com/tiredofit/docker-postgres/blob/12/examples/docker-compose.yml

**Comment by joergmschulz** [comment]
Thank you very much!

**Comment by joergmschulz** [comment]
nice
