### ISSUE TITLE
Upgrade 13-> 15 howto?

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-postgres#7]
does the image have an option to automatically upgrade from an old version (e.g. 13) to 15, or do I need to manually create a container with both versions (13,15) and run pg_upgrade in this container instead?

**Comment by tiredofit** [comment]
You would have to do the latter to perform an upgrade. Postgresql makes it difficult to upgrade from major versions. Alternatively you could just use the db-backup image I wrote and backup and use the `restore` script onto a new 15 instance. There are significant changes to the 15 image where I feel its worth it.

**Comment by joergmschulz** [comment]
Thank you - will go for the latter.

**Comment by joergmschulz** [comment]
**This is how I've done it**
if you have multiple databases the easiest thing is to create a new database directory and:
```
(close all apps)
cd /yourVersion13Docker
docker compose exec -T --user postgres postgres-db pg_dumpall > /tmp/pg.sql
docker compose exec -T --user postgres postgres-db pg_dumpall -r > /tmp/pgr.sql
 docker compose down --rmi all -v 
(deactivate container)
cd /yourVersion15Docker
cat /tmp/pgr.sql|  docker compose exec --user postgres pg15-db  psql
cat /tmp/pg.sql|  docker compose exec --user postgres pg15-db  psql
(rename the new container to the old name, restart, start all applications, done)
```
now you have an old data and pg directory and a new one - when all is working, you can remove the old stuff.

**Comment by tiredofit** [comment]
Great! Thanks for sharing.
