### ISSUE TITLE
Version 3.20 not working on docker.io

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-postgres#8]
while a 
`build: https://github.com/tiredofit/docker-postgres.git#15-3.2.0`
in docker-compose.yml works perfectly, the version in docker.io does not - the filesize is much smaller than for the version before, and the PG executable binaries seem to be missing:
<img width="1206" alt="grafik" src="https://github.com/tiredofit/docker-postgres/assets/6523646/3c74d778-6dc4-45c9-bc6c-c001414f57e5">

**Comment by tiredofit** [comment]
Thanks, Github seemed to have multiple outages last week which broke alot of the builds. I'm pushing manually a `15` and a `15-3.2.0`.

**Comment by joergmschulz** [comment]
the most recent version works now! docker pull tiredofit/postgres:15-3.2.0, Thanks a lot

**Comment by joergmschulz** [comment]
same thing  for 3.21: not working, filesize of image is 65MB only instead of 140

**Comment by tiredofit** [comment]
Thanks, I appreciate you letting me know. Looks like the Zabbix Plugin is causing some pain. I'll have a new fix shortly.

EDIT `15-3.2.2` should solve.

**Comment by joergmschulz** [comment]
confirming - 15.3.2.2 runs

**Comment by theAkito** [comment]
Had this issue with `15-latest` from 6 weeks ago, as of now.
Restarted, still did not work.

Used some old version, worked again.

Then, I realised, I needed to add `pull_policy: always` to the database service inside the `docker-compose.yml`, so it always pulls the actually newest version.
